{
 "title": "Pod Resource Details - CPU & Memory",
 "tags": [
  "kubernetes",
  "pods",
  "cpu",
  "memory",
  "resources"
 ],
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(kube_pod_info{namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pod CPU Usage - $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$pod\",container!=\"\",container!=\"POD\"}[5m])) by (pod, container)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage - $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",pod=~\"$pod\",container!=\"\",container!=\"POD\"}) by (pod, container)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Pod CPU Throttling",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Throttled Seconds" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"$namespace\",pod=~\"$pod\",container!=\"\",container!=\"POD\"}[5m])) by (pod, container)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Pod Memory Working Set",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"$pod\",container!=\"\",container!=\"POD\"}) by (pod, container)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "All Pods CPU Usage in Namespace",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"\",container!=\"POD\"}[5m])) by (namespace, pod, container)"
    }
   ]
  },
  {
   "title": "All Pods Memory Usage in Namespace",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",container!=\"\",container!=\"POD\"}) by (namespace, pod, container)"
    }
   ]
  },
  {
   "title": "Pod Resource Limits vs Usage",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=~\"$pod\",resource=\"cpu\"}) by (namespace, pod, container)",
     "legendFormat": "CPU Limit"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$pod\",container!=\"\",container!=\"POD\"}[5m])) by (namespace, pod, container)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=~\"$pod\",resource=\"memory\"}) by (namespace, pod, container)",
     "legendFormat": "Memory Limit"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",pod=~\"$pod\",container!=\"\",container!=\"POD\"}) by (namespace, pod, container)",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Network I/O by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "Receive - {{pod}}"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "Transmit - {{pod}}"
    }
   ]
  },
  {
   "title": "Filesystem Usage by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "bytes", "label": "Filesystem Usage" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"$namespace\",pod=~\"$pod\",container!=\"\",container!=\"POD\"}) by (pod, container)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  }
 ]
}