# Grafana datasources configuration for Docker Compose setup
# This file is automatically loaded by Grafana on startup

apiVersion: 1

# List of datasources to insert/update
datasources:
  # Prometheus datasource
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
    version: 1

