# Prometheus configuration for Docker Compose setup
# This is a standalone Prometheus config for containerized deployment

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'docker-compose'
    environment: 'development'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

# Load alert rules
rule_files:
  - '/etc/prometheus/alerts.yaml'

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Node Exporter (host metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'
          instance: 'docker-host'

  # Health Checker application (if it exposes metrics)
  - job_name: 'health-checker'
    static_configs:
      - targets: ['health-checker:8080']
        labels:
          service: 'health-checker'

  # Kubernetes cluster metrics (via port-forward or service)
  # Uncomment if you have Kubernetes metrics exposed
  # - job_name: 'kubernetes-apiservers'
  #   kubernetes_sd_configs:
  #     - role: endpoints
  #   scheme: https
  #   tls_config:
  #     ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  #   bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

  # Docker containers (if Docker metrics are exposed)
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
        labels:
          service: 'docker'

